# models
model :space_marine, {
  name: "Space Marine",
  ws: 4,
  bs: 4,
  s: 4,
  t: 4,
  i: 4,
  w: 1,
  a: 1,
  ld: 9,
  sv: "3+"
}
model :veteran
model :attack_bike
model :azrael
model :belial
model :chaplain
model :company_master
model :ezekiel
model :interrogator_chaplain
model :interrogator_chaplain_jumppack
model :interrogator_chaplain_terminator
model :librarian
model :ravenwing_biker
model :sammael
model :scout
model :scout_sergeant
model :servitor
model :techmarine
model :terminator
model :terminator_sergeant
model :drop_pod
model :land_raider
model :land_raider_crusader
model :land_speeder
model :predator
model :razorback
model :rhino
model :vindicator
model :whirlwind
model :dreadnaught
