--- 
list: 
  description: Scouts
  schematic: scouts/scout_squad
  author: Codiphi Developer
  author_email: development@flipstone.com
  variant: Base
  unit: 
  - type: scout_squad
    model: 
    - type: scout
      count: 4
    - type: scout_sergeant
      count: 1
